name: Deploy to Production

on:
  push:
    branches: [ main ]  # 當推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        # 複製專案文件到伺服器
        rsync -avz --exclude '.git*' \
                   --exclude 'output_files' \
                   ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/

        # SSH 到伺服器執行部署命令
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && \
          # 確保 output_files 目錄存在並設置權限
          mkdir -p output_files && \
          chmod -R 777 output_files && \
          # 重建並重啟容器
          docker-compose down && \
          docker-compose build --no-cache && \
          docker-compose up -d && \
          # 清理不使用的映像檔
          docker image prune -f"
